#!/usr/bin/env sh
# Regenerates nginx/snippets/cloudflare-realip.conf from Cloudflare's published
# edge IP ranges. Run it occasionally (the ranges change rarely), review the
# diff, commit, and reload nginx.
set -eu
cd "$(dirname "$0")/.."
out=nginx/snippets/cloudflare-realip.conf
v4=$(curl -fsS https://www.cloudflare.com/ips-v4)
v6=$(curl -fsS https://www.cloudflare.com/ips-v6)
{
  echo "# Generated by scripts/update_cf_ranges.sh on $(date -u +%Y-%m-%d). Do not edit by hand."
  echo "#"
  echo "# The site sits behind Cloudflare, so \$remote_addr is a Cloudflare edge IP"
  echo "# shared by many visitors. For requests that really come from Cloudflare,"
  echo "# replace it with the visitor's IP from CF-Connecting-IP. Anyone reaching the"
  echo "# origin directly keeps their own address and cannot spoof the header."
  echo "# (Engineering review H1.)"
  for r in $v4 $v6; do echo "set_real_ip_from $r;"; done
  echo "real_ip_header CF-Connecting-IP;"
} > "$out"
echo "wrote $out"
